#!/bin/sh
# Written and tested on a stock Alpine 3.16
# Requirements:
# - jq
# - zip

set -e pipefail

mkdir -p dist

allow_list='src/ README.md LICENSE manifest.json'
archive_name=`jq -r '"\(.name)-firefox-\(.version)"' manifest.json`

zip -0 -r "dist/$archive_name.zip" $allow_list

echo [scripts/pack] zipped the extension to dist/$archive_name.zip
