#!/bin/sh
# Written and tested on a stock Alpine 3.16
# Requirements:
# - jq
# - zip
# - git

set -e pipefail

mkdir -p dist

archive_name=`jq -r '"\(.name)-firefox-\(.version)-src"' manifest.json`
git archive --format zip --output "dist/$archive_name.zip" HEAD

echo [scripts/zip-for-review] zipped the source code to dist/$archive_name.zip
