// This file is automatically generated by a pre-commit hook from data/services.json
// Take a look at scripts/gen-dictionary
export const base = {
  'instagram.com': 'bibliogram.art',
  'medium.com': 'scribe.rip',
  'music.youtube.com': 'beatbump.ml',
  'quora.com': 'quetre.herokuapp.com',
  'reddit.com': 'libreddit.nl',
  'twitter.com': 'nitter.nl',
  'youtube.com': 'piped.kavin.rocks'
}

export const instances = {
  'inv.bp.projectsegfau.lt': 'piped.kavin.rocks',
  'inv.riverside.rocks': 'piped.kavin.rocks',
  'inv.vern.cc': 'piped.kavin.rocks',
  'invidious.esmailelbob.xyz': 'piped.kavin.rocks',
  'invidious.flokinet.to': 'piped.kavin.rocks',
  'invidious.kavin.rocks': 'piped.kavin.rocks',
  'invidious.namazso.eu': 'piped.kavin.rocks',
  'invidious.nerdvpn.de': 'piped.kavin.rocks',
  'invidious.osi.kr': 'piped.kavin.rocks',
  'invidious.projectsegfau.lt': 'piped.kavin.rocks',
  'invidious.sethforprivacy.com': 'piped.kavin.rocks',
  'invidious.slipfox.xyz': 'piped.kavin.rocks',
  'invidious.snopyta.org': 'piped.kavin.rocks',
  'invidious.tiekoetter.com': 'piped.kavin.rocks',
  'invidious.weblibre.org': 'piped.kavin.rocks',
  'new.reddit.com': 'libreddit.nl',
  'old.reddit.com': 'libreddit.nl',
  'vid.puffyan.us': 'piped.kavin.rocks',
  'y.com.sb': 'piped.kavin.rocks',
  'yewtu.be': 'piped.kavin.rocks',
  'youtube.076.ne.jp': 'piped.kavin.rocks',
  'yt.artemislena.eu': 'piped.kavin.rocks'
}

