// This file is automatically generated by a pre-commit hook from data/services.json
// Take a look at scripts/gen-dictionary
export const base = {
  'instagram.com': 'bibliogram.art',
  'medium.com': 'scribe.rip',
  'music.youtube.com': 'beatbump.ml',
  'quora.com': 'quetre.herokuapp.com',
  'reddit.com': 'libreddit.nl',
  'twitter.com': 'nitter.nl',
  'youtube.com': 'piped.kavin.rocks'
}

export const instances = {
  'inv.riverside.rocks': 'piped.kavin.rocks',
  'new.reddit.com': 'libreddit.nl',
  'old.reddit.com': 'libreddit.nl',
  'yewtu.be': 'piped.kavin.rocks'
}

